In [9]:
import numpy as np
import pandas as pd 

In [13]:

np.random.seed(23) 

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1

mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1['target'] = 0

df = pd.concat([df, df1], ignore_index=True)
df = df.sample(40)

In [15]:
df.head(2)

feature1  feature2  feature3  target
2  -0.367548 -1.137460 -1.322148       1
34  0.177061 -0.598109  1.226512       0

In [17]:
# %pip install plotly

In [ ]:
# %pip install nbformat

Note: you may need to restart the kernel to use updated packages.


In [30]:
import plotly.express as px
#y_train_trf = y_train.astype(str)
fig = px.scatter_3d(df, x=df['feature1'], y=df['feature2'], z=df['feature3'],
              color=df['target'].astype('str'))
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

# fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'color=1<br>feature1=%{x}<br>feature2=%{y}<br>feature3=%{z}<extra></extra>',
              'legendgroup': '1',
              'marker': {'color': '#636efa',
                         'line': {'color': 'DarkSlateGrey', 'width': 2},
                         'size': 12,
                         'symbol': 'circle'},
              'mode': 'markers',
              'name': '1',
              'scene': 'scene',
              'showlegend': True,
              'type': 'scatter3d',
              'x': {'bdata': ('NH+biOiF179B9VhOe+vaP3UXmWq1fv' ... '5vFJe/FZ26DqZG9D+1VBZ/K1v8Pw=='),
                    'dtype': 'f8'},
              'y': {'bdata': ('kOrC7ggz8r8NGQXo+VfaP0/7V7d6h+' ... 'MgfYs/kwOAlKA5xj/B9siixDzWvw=='),
                    'dtype': 'f8'},
              'z': {'bdata': ('Gz4gKYQn9b9TmEbkSEKyv6yJIWPLve' ... 'RC8+0/JVQemXOS87/dI2zIyXHlPw=='),
                    'dtype': 'f8'}},
             {'hovertemplate': 'color=0<br>feature1=%{x}<br>feature2=%{y}<br>feature3=%{z}<extra></extra>',
              'legendgroup': '0',
              'marker': {'color': '#EF553B',
                         'line': {'color': 'DarkSlateGrey', 'width': 2},
                         'size': 12,
                         'symbol': 'circle'},
              'mode': 'markers',
              'name': '0',
              'scene': 'scene',
              'showlegend': True,
              'type': 'scatter3d',
              'x': {'bdata': ('cB4YBfKpxj8RrEKwX832P4T5z06iyw' ... '2JMco/UuE+sp725z+n98TRC77zPw=='),
                    'dtype': 'f8'},
              'y': {'bdata': ('JvSht7Uj47+/Yffh9A73P0iE1ULHfc' ... 'XDn4e/1LzUyLC+BEBwf5DSqAWrPw=='),
                    'dtype': 'f8'},
              'z': {'bdata': ('y9Aoxsqf8z/c2FLsJV7HP0lFrBXsEv' ... '3MNAlA+CcZWau78j+AkGAiqr3Qvw=='),
                    'dtype': 'f8'}}],
    'layout': {'legend': {'title': {'text': 'color'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'scene': {'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
                         'xaxis': {'title': {'text': 'feature1'}},
                         'yaxis': {'title': {'text': 'feature2'}},
                         'zaxis': {'title': {'text': 'feature3'}}},
               'template': '...'}
})

### Doing PCA 
1. Apply standard scaling 
2. find covariance Matrix 
3. finding EVector and EVs 

In [ ]:
## Step - 1 Apply Standard Scaling 

from sklearn.preprocessing import StandardScaler 

scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])
## Sabko center m kar diya 

## Step-2 -- Find Covarinace Matrix 
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1], df.iloc[:,2]]) ## Co-variance of these these 
## co-variance - relation X And Y to to all these columns 

covariance_matrix


array([[1.02564103, 0.20478114, 0.080118  ],
       [0.20478114, 1.02564103, 0.19838882],
       [0.080118  , 0.19838882, 1.02564103]])

In [33]:
## Step - 3 -- Finding EV and Evectors 

eigen_values , eigen_vectors = np.linalg.eig(covariance_matrix)

In [34]:
print('eigen_values', eigen_values)
print('eigen_vectors ', eigen_vectors)

eigen_values [1.3536065  0.94557084 0.77774573]
eigen_vectors  [[-0.53875915 -0.69363291  0.47813384]
 [-0.65608325 -0.01057596 -0.75461442]
 [-0.52848211  0.72025103  0.44938304]]


In [35]:
%pylab inline 

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [36]:
from matplotlib import pyplot as plt 
from mpl_toolkits.mplot3d import Axes3D , proj3d
from matplotlib.patches import FancyArrowPatch

In [38]:

class Arrow3D(FancyArrowPatch):
    def __init__(self, xs, ys, zs, *args, **kwargs):
        FancyArrowPatch.__init__(self, (0,0), (0,0), *args, **kwargs)
        self._verts3d = xs, ys, zs

    def draw(self, renderer):
        xs3d, ys3d, zs3d = self._verts3d
        xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, renderer.M)
        self.set_positions((xs[0],ys[0]),(xs[1],ys[1]))
        FancyArrowPatch.draw(self, renderer)

fig = plt.figure(figsize=(7,7))
ax = fig.add_subplot(111, projection='3d')

ax.plot(df['feature1'], df['feature2'], df['feature3'], 'o', markersize=8, color='blue', alpha=0.2)
ax.plot([df['feature1'].mean()], [df['feature2'].mean()], [df['feature3'].mean()], 'o', markersize=10, color='red', alpha=0.5)
for v in eigen_vectors.T:
    a = Arrow3D([df['feature1'].mean(), v[0]], [df['feature2'].mean(), v[1]], [df['feature3'].mean(), v[2]], mutation_scale=20, lw=3, arrowstyle="-|>", color="r")
    ax.add_artist(a)
ax.set_xlabel('x_values')
ax.set_ylabel('y_values')
ax.set_zlabel('z_values')

plt.title('Eigenvectors')

# plt.show()

Text(0.5, 0.92, 'Eigenvectors')

Error in callback <function _draw_all_if_interactive at 0x000002430827F380> (for post_execute), with arguments args (),kwargs {}:


AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection'

AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection'

<Figure size 700x700 with 1 Axes>

In [40]:
eigen_vectors

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442],
       [-0.52848211,  0.72025103,  0.44938304]])

In [39]:
## PcA In scikit-learn 

pc = eigen_vectors[0:2]
pc

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442]])

In [41]:
transformed_df = np.dot(df.iloc[:,0:3],pc.T)

In [42]:
new_df = pd.DataFrame(transformed_df,columns=['PC1','pC2'])

new_df['target'] = df['target'].values

In [43]:
new_df.head()

PC1       pC2  target
0  0.599433  1.795862       1
1  1.056919 -0.212737       0
2 -0.271876  0.498222       1
3 -0.621586  0.023110       1
4  1.567286  1.730967       1